### ISSUE TITLE
Request Namespaced Alias Wildcards

### ISSUE THREAD

**Issue by adrianug** [TYPO3/class-alias-loader#1]
it seems to be difficult if there are a lot of classes in a namespace and you must define them one by one, so its would be nice if supported wilcards, something like 

```php
'Model\*' => 'My\Project\Model\$1' 
```

and act like 

```php
$article = new Model\Article(); // My\Project\Model\Article;
```

whether this is possible or already available ?

**Comment by helhum** [comment]
I'm sorry, but there are no plans to implement such functionality.

This package is meant to provide backwards compatibility for a period of time, not for regular usage.
You will need to write a generator that scans for your classes and generates the alias map.
