### ISSUE TITLE
Update from v1.0.1 to v1.1.0 fails with TypeError

### ISSUE THREAD

**Issue by bnf** [TYPO3/class-alias-loader#16]
The commit https://github.com/TYPO3/class-alias-loader/commit/a63a582e077d89786e38b30954c58a98a22f0105 changed the signature of `ClassAliasMapGenerator::__construct` which causes a `TypeError` because versions seem to be mixed during a `composer update`.

```
Writing lock file
Generating autoload files
Generating class alias map file
Inserting class alias loader into main autoload.php file
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating typo3/class-alias-loader (1.0.1 => v1.1.0): Loading from cache
Writing lock file
Generating autoload files
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to TYPO3\ClassAliasLoader\ClassAliasMapGenerator::__construct() must be an instance of TYPO3\ClassAliasLoader\Config or null, bool given, called in phar:///home/ben/.local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code on line 83 and defined in /home/ben/tmp/test-class-alias-loader/vendor/typo3/class-alias-loader/src/ClassAliasMapGenerator.php:49
Stack trace:
#0 phar:///home/ben/.local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code(83): TYPO3\ClassAliasLoader\ClassAliasMapGenerator->__construct(Object(Composer\Composer), Object(Composer\IO\ConsoleIO), false)
#1 [internal function]: TYPO3\ClassAliasLoader\Plugin_composer_tmp1->onPostAutoloadDump(Object(Composer\Script\Event))
#2 phar:///home/ben/.local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(176): call_user_func(Array, Object(Composer\Script\Event))
#3 phar:///home/ben/.local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\E in /home/ben/tmp/test-class-alias-loader/vendor/typo3/class-alias-loader/src/ClassAliasMapGenerator.php on line 49

Fatal error: Uncaught TypeError: Argument 3 passed to TYPO3\ClassAliasLoader\ClassAliasMapGenerator::__construct() must be an instance of TYPO3\ClassAliasLoader\Config or null, bool given, called in phar:///home/ben/.local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code on line 83 and defined in /home/ben/tmp/test-class-alias-loader/vendor/typo3/class-alias-loader/src/ClassAliasMapGenerator.php:49
Stack trace:
#0 phar:///home/ben/.local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code(83): TYPO3\ClassAliasLoader\ClassAliasMapGenerator->__construct(Object(Composer\Composer), Object(Composer\IO\ConsoleIO), false)
#1 [internal function]: TYPO3\ClassAliasLoader\Plugin_composer_tmp1->onPostAutoloadDump(Object(Composer\Script\Event))
#2 phar:///home/ben/.local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(176): call_user_func(Array, Object(Composer\Script\Event))
#3 phar:///home/ben/.local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\E in /home/ben/tmp/test-class-alias-loader/vendor/typo3/class-alias-loader/src/ClassAliasMapGenerator.php on line 49
```

Steps to reproduce:

```
mkdir test-class-alias-loader
cd test-class-alias-loader
composer init -n
composer require typo3/cms-base-distribution typo3/class-alias-loader:1.0.1
composer require typo3/class-alias-loader:1.1.0
```

Note: This was discovered by TYPO3 nightly tests:
https://bamboo.typo3.com/browse/CORE-GTN95-81
https://bamboo.typo3.com/browse/CORE-GTN-84

**Comment by px-flo** [comment]
Same from 1.0.2 -> 1.1.0

**Comment by helhum** [comment]
Does this error persist when running composer install a second time, or is it only present for the update call?

**Comment by px-flo** [comment]
Only the first time. On a downgrade an other error occurred (within the first run too). Run it twice will solve the problem.

**Comment by bnf** [comment]
No, another `composer install` or `composer dump-autoload` works because versions are no longer mixed.

Still, I think we need to add a new policy for these kind of changes:

- Add a versioned vendor name for *all* classes that are called in events from `composer`
- Everytime a method signature is changed the version number for the vendor name needs to be increased

That means this package would have two vendor names:

- `TYPO3\ClassAliasLoader` for `TYPO3\ClassAliasLoader\ClassAliasMap`
- `TYPO3\ClassAliasLoaderEventsV120` for the callbacks used in version 1.2.0

**Comment by helhum** [comment]
> Still, I think we need to add a new policy for these kind of changes

To be really safe it would mean duplicating code and keeping that duplicated code for enternety, as upgrades from e.g. 1.0.0 can always happen.

While I strive to mitigate such issues, it is really hard to avoid them especially when renovating code and concepts at such level.

I personally think it is not worth the effort (duplicating plugin and all API code for every signature change), but I'm fine if it is decided that we really need it.

What would be helpful though is adding a test suite to cover the upgrade scenario, so that such issue are caught before code is released.

**Comment by helhum** [comment]
Oh, and I just realised, that these kind of errors go away with Composer 2.0, which allows smooth upgrade from 1.0.2 to 1.1.0 without errors and full functionality
