### ISSUE TITLE
Class not found with 1.1.1

### ISSUE THREAD

**Issue by georgringer** [TYPO3/class-alias-loader#17]
SInce update from 1.0.2 to 1.1.1 I get exceptions from class loader

```
Class 'TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper' not found
in /app/web/typo3conf/ext/vhs/Classes/ViewHelpers/Uri/TypolinkViewHelper.php line 45
```

this shipped ViewHelper in vhs version `5.2.0` is marked as deprecated and yes, the mentioned class can't be loaded. The error is shown even if the VH is not used.

downgrading to version 1.0.2 fixes the problem

```json
"require": {
        "php": "^7.2",
        "ext-curl": "*",
        "ext-json": "*",
        "apache-solr-for-typo3/solr": "^9",
        "bithost-gmbh/powermail_fastexport": "^1.0",
        "fluidtypo3/fluidpages": "^5",
        "fluidtypo3/flux": "9.2.0",
        "fluidtypo3/vhs": "^5",
        "helhum/typo3-console": "^5",
        "ichhabrecht/mask-export": "^2.4",
        "in2code/powermail": "^7",
        "koninklijke-collective/my-redirects": "^4.2",
        "mask/mask": "^4",
        "netresearch/rte-ckeditor-image": "^9.0",
        "sup7even/mailchimp": "dev-master",
        "t3g/blog": "^9",
        "typo3/cms-belog": "^9.5",
        "typo3/cms-beuser": "^9.5",
        "typo3/cms-extbase": "^9.5",
        "typo3/cms-extensionmanager": "^9.5",
        "typo3/cms-felogin": "^9.5",
        "typo3/cms-filelist": "^9.5",
        "typo3/cms-fluid": "^9.5",
        "typo3/cms-fluid-styled-content": "^9.5",
        "typo3/cms-frontend": "^9.5",
        "typo3/cms-info": "^9.5",
        "typo3/cms-info-pagetsconfig": "^9.5",
        "typo3/cms-install": "^9.5",
        "typo3/cms-lang": "^9.5",
        "typo3/cms-linkvalidator": "^9.5",
        "typo3/cms-lowlevel": "^9.5",
        "typo3/cms-recordlist": "^9.5",
        "typo3/cms-recycler": "^9.5",
        "typo3/cms-reports": "^9.5",
        "typo3/cms-rte-ckeditor": "^9.5",
        "typo3/cms-saltedpasswords": "^9.5",
        "typo3/cms-scheduler": "^9.5",
        "typo3/cms-setup": "^9.5",
        "typo3/cms-sv": "^9.5",
        "typo3/cms-redirects": "^9.5",
        "typo3/cms-tstemplate": "^9.5",
        "typo3/cms-viewpage": "^9.5",
        "typo3/class-alias-loader": "^1.1"
    },
```

**Comment by helhum** [comment]
> SInce update from 1.0.2 to 1.1.1 I get exceptions from class loader

Please verify, whether a `composer dumpautoload` directly after the upgrade of this package fixes your issue.

**Comment by helhum** [comment]
> The error is shown even if the VH is not used
how come you made this conclusion?

**Comment by georgringer** [comment]
and now I can't reproduce it anymore and everything is working fine

> Please verify, whether a composer dumpautoload directly after the upgrade of this package fixes your issue.
I did that and it is also automatically done with composer update/install

> how come you made this conclusion?
because not even the TYPO3 backend login worked anymore

sorry wasting your time

**Comment by helhum** [comment]
@georgringer 

> and now I can't reproduce it anymore and everything is working fine
That is because you ran `composer install` or `composer dumpautoload` again at least once.

Should we make [this](https://github.com/TYPO3/class-alias-loader/blob/ee417366a289871460910ae1703976e9903a5e80/src/ClassAliasMapGenerator.php#L67) an error to make the warning message more prominent?

**Comment by helhum** [comment]
> because not even the TYPO3 backend login worked anymore

Well, then the code tried to instaciate this class, otherwise PHP would not have complained.

> I did that and it is also automatically done with composer update/install

I'm pretty much aware of that Composer does that. But directly after the upgrade, the old plugin code is executed, which does not do what is required for the new state. Therefore an **additional** call is required once

**Comment by helhum** [comment]
> sorry wasting your time

No worries. Such things won't happen any more with Composer 2.0, but are only very hard to avoid with 1.x and causes confusion all the time

**Comment by georgringer** [comment]
> Should we make this an error to make the warning message more prominent?

if possible, yes and if it is by outputting it 10 times
![bart-simpson-generator](https://user-images.githubusercontent.com/1905663/81289921-778d4680-9067-11ea-9964-282013ff553e.jpg)

**Comment by helhum** [comment]
Looks like this now:

<img width="669" alt="Error message" src="https://user-images.githubusercontent.com/904370/81296217-dbb50800-9071-11ea-8192-4ecc2b98a542.png">
