### ISSUE TITLE
Deprecations with PHP 8.4

### ISSUE THREAD

**Issue by andreaskienast** [TYPO3/class-alias-loader#31]
With PHP 8.4, at least one deprecation is revealed thanks to our CI:

```
Deprecation Notice: TYPO3\ClassAliasLoader\IncludeFile::__construct(): Implicitly marking parameter $filesystem as nullable is deprecated, the explicit nullable type must be used instead in /builds/typo3/CI/cms/vendor/typo3/class-alias-loader/src/IncludeFile.php:51
```

However, nullable properties are allowed since PHP 7.1 only, violating the PHP version constraints in the composer.json file.

**Comment by helhum** [comment]
I think meanwhile it is fine to raise minimum
php requirements to at least 7.4
